### ISSUE TITLE
Want to add content(Platforms, blogs, websites) to Hacking, Git 

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [ACM-Thapar/CS_COURSE_GUIDE#85]
I have a good experience with Git, GitHub and Cybersecurity (1 and half year till now), I see Hacking and Git directories incomplete in the repo. Should I go further and add the content?

**Comment by JhndaCoder** [comment]
Sure sure go ahead
Contributions are always welcomed and appreciated

**Comment by umangbadhwar** [comment]
I have a useful pdf explaining Git commands. Can I contribute to the Git content repo?

**Comment by ShubhamJagtap2000** [comment]
> > I have a useful pdf explaining Git commands. Can I contribute to the Git content repo?
> 
> Can you please add it in the form of markdown

Yes. Actually, this is the main reason I created .md file because viewing PDF is always a hectic task on GitHub.
